[project]
name = "fincli"
version = "0.1.1"
description = "A free finance cli app that handles day to day finance tasks and operations"
readme = "README.md"
authors = [
    { name = "snowdingo", email = "snowdingo.tech@gmail.com" }
]
keywords = ["finance","cli","utility"]
requires-python = ">=3.13"
dependencies = [
    "typer>=0.27.1",
    "pytz>=2026.3.post1",
    "requests>=2.34.2",
]

[project.scripts]
fincli = "fincli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/snowdingo/fincli"
Repository="https://github.com/snowdingo/fincli.git"
"Issue Tracker" = "https://github.com/snowdingo/fincli/issues"